#!/bin/sh

# git-remote-list - list remote repositories.
# Copyright (C) 2009  Will Harris
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if [[ "$REPO_SERVER" == "" ]]; then
        echo "REPO_SERVER not set"
        exit 1
fi

if [[ "$REPO_SERVER_GIT_PATH" == "" ]]; then
        echo "REPO_SERVER_GIT_PATH not set"
        exit 1
fi

if ! ssh $REPO_SERVER "cd $REPO_SERVER_GIT_PATH && ls"; then
        echo "Could not list repos"
        exit 1
fi
