#!/bin/sh

# srcgrep - search a source tree.
# Copyright (C) 2008  Will Harris
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

find . \( -name "*.py" \
       -o -name "*.java" \
       -o -name "*.jsp" \
       -o -name "*.eca" \
       -o -name "*.js" \
       -o -name "*.c" \
       -o -name "*.cc" \
       -o -name "*.h" \
       -o -name "*.css" \
       -o -name "*.tpl" \
       -o -name "*.eca" \
       -o -name "*.sh" \
       -o -name "RELEASE" \
       -o -name "applicationContext.xml" \
       -o -name "spring-servlet.xml" \
       -o -name "web.xml" \
       -o -name "*.idl" \
       -o -name "*.tag" \) -exec grep --color --with-filename "$@" {} \;
