#!/usr/bin/env python

# wdiff - frontend to opendiff.
# Copyright (C) 2008  Will Harris
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import sys
import os
import time

COMMAND = "/usr/bin/opendiff"
args = [COMMAND]

skipping = True
for arg in sys.argv:
    if skipping:
        skipping = False
    elif arg == "-L":
        skipping = True
    elif arg[0] != "-":
        args.append(arg)

if len(args) > 3:
    args.insert(2, "-ancestor")

print COMMAND, " ".join(args)
os.spawnl(os.P_WAIT, COMMAND, *args)
time.sleep(5)
