#!/usr/bin/env python
import sys
import os
import time

COMMAND = "/usr/bin/opendiff"
args = [COMMAND]

skipping = True
for arg in sys.argv:
    if skipping:
        skipping = False
    elif arg == "-L":
        skipping = True
    elif arg[0] != "-":
        args.append(arg)

if len(args) > 3:
    args.insert(2, "-ancestor")

print COMMAND, " ".join(args)
os.spawnl(os.P_WAIT, COMMAND, *args)
time.sleep(5)
